{% set name = "docsteady" %}
{% set version =  [GIT_DESCRIBE_TAG, GIT_DESCRIBE_NUMBER, GIT_DESCRIBE_HASH]|join('_') %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: ../

build:
  entry_points:
    - docsteady = docsteady:cli
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.11
    - setuptools-scm
    - pip
  run:
    - python >=3.11
    - requests
    - pypandoc
    - arrow
    - jinja2
    - click
    - beautifulsoup4
    - marshmallow <3
    - setuptools-scm
    - pymysql
    - pillow

test:
  rootdir: ../
  commands:
    - pytest
    - docsteady --help
  requires:
    - pytest

about:
  home: https://github.com/lsst-dm/docsteady
  summary: Docsteady Test Document Generator
  license: GPL-2.0-or-later
  license_file: LICENSE

