{% set name = "docsteady" %}
{% set version =  [GIT_DESCRIBE_TAG, GIT_DESCRIBE_NUMBER]|join('_') %}
# Took out GIT-DESCRIBE_HASH it make shte version odd looking.

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  path: ../

build:
  entry_points:
    - docsteady = docsteady:cli
  noarch: python
  always_include_files:
    - pyproject.toml
    - tests
    - docsteady
  script: {{ PYTHON }} -m pip install --no-deps --ignore-installed . -vv

requirements:
  build:
    - python >=3.11
  host:
    - python >=3.11
    - setuptools-scm
    - pip
  run:
    - python >=3.11
    - requests
    - pypandoc
    - arrow
    - jinja2
    - click
    - beautifulsoup4
    - marshmallow <3
    - setuptools-scm
    - pillow
  test:
    pytest

test:
  commands:
    - pytest
  source_files:
    - pyproject.toml
  requires:
    - pytest

about:
  home: https://github.com/lsst-dm/docsteady
  summary: Docsteady Test Document Generator
  license: GPL-2.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - womullan
