name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install linters
        run: |
          python -m pip install --upgrade pip
          python -m pip install flake8 pybtex

      - name: Run flake8
        run: flake8

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.7

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r docs/requirements.txt
          python -m pip install ltd-conveyor

      - name: Compile documentation
        run: |
          cd docs
          make html

      - name: Upload documentation
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          ltd upload --product docsteady --gh --dir docs/_build/html

