name: CI

on: [push, pull_request]

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ">3.11"

      - name: Run pre-commit
        uses: pre-commit/action@v3.0.0

      - name: Install Python dependencies
        run: |
          sudo apt-get -y install pandoc
          python -m pip install --upgrade pip
          python -m pip install -r requirements/main.txt -r requirements/dev.txt

  test:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python:
          - ">3.11"

    steps:
      - uses: actions/checkout@v3

      - name: Run tox
        uses: lsst-sqre/run-tox@v1
        with:
          python-version: ${{ matrix.python }}
          tox-envs: "py,coverage-report,typing"

  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ">3.11"

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/main.txt
          python -m pip install -r requirements/dev.txt
          python -m pip install .


      - name: Compile documentation
        run: |
          cd docs
          make html

      - name: Upload documentation
        if: ${{ github.event_name == 'push' }}
        env:
          LTD_PASSWORD: ${{ secrets.LTD_PASSWORD }}
          LTD_USERNAME: ${{ secrets.LTD_USERNAME }}
        run: |
          ltd upload --product docsteady --gh --dir docs/_build/html
